# Generated by Django 3.1 on 2020-08-12 04:21

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200812_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='id',
            field=models.CharField(default=utils.models.get_uuid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=utils.models.get_uuid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
